Repository deyvisnvg/projectunidad_7, pull requests merged in 2023-01, with the labels that each got.

#1 Estructura inicial y creación de modelo User
  .gitignore
  components/playlist/index.ts
  components/songs/index.ts
  components/user/index.ts
  nodemon.json
  package.json
  prisma/schema.prisma
  router/router.ts
  src/app.ts
  src/index.ts
  tsconfig.json
Labels: enhancement

#2 Se agrego el modelo Song
  prisma/schema.prisma
Labels: create

#6 Song
  src/components/songs/controller.ts
  src/components/songs/index.ts
  src/index.ts
  src/router/router.ts
Labels: enhancement, create

#10 modificando el modelo song y creando funciones
  prisma/schema.prisma
  src/components/songs/controller.ts
  src/components/songs/index.ts
Labels: enhancement, create

#12 modifique el schema y agregando la playlist
  prisma/schema.prisma
  src/components/playlist/controller.ts
  src/components/playlist/index.ts
  src/router/router.ts
Labels: enhancement, create

#13 modificaciones en el componente song
  prisma/schema.prisma
  src/components/songs/controller.ts
  src/components/songs/index.ts
  src/lib/jwt.ts
Labels: enhancement, create

#14 autenticando la playlist
  src/components/playlist/controller.ts
  src/components/playlist/index.ts
Labels: enhancement

#15 readme funcionalidades del component user
  README.md
Labels: enhancement

#17 Readme bill
  README.md
Labels: create

#18 Readme1
  README.md
Labels: enhancement

#21 modificaciones readme componente song
  README.md
Labels: enhancement

#19 edite los errores de la info playlist
  README.md
Labels: enhancement
